Fix Python TaskMetrics.__init__
`gatherAccumulable` was removed from the constructor from the parallel
Scala TaskMetrics class; however, the Python constructor was not
updated.

py4j.Py4JException: Constructor ch.cern.sparkmeasure.TaskMetrics([class org.apache.spark.sql.SparkSession, class java.lang.Boolean]) does not exist